# Site settings
title: Scalable Software Architecture
email: soren@linux2go.dk
description: > # this means to ignore newlines until "baseurl:"
  Learn about scalable software architecture.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.scalablesoftwarearchitecture.com" # the base hostname & protocol for your site
twitter_username: cloudsoren
github_username:  sorenh
fbapp_id: 1872714046294613
google_analytics_id: UA-85166462-1

# Build settings
markdown: kramdown
