# Site settings
title: Sensible Software Architecture
email: soren@linux2go.dk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astronomer-sheila-38188.netlify.com/" # the base hostname & protocol for your site
twitter_username: cloudsoren
github_username:  sorenh

# Build settings
markdown: kramdown
